import { Alert } from "./types";
import { mockPatients } from "./data";

export const mockAlerts: Alert[] = [
  {
    id: "alert1",
    patientId: "p2",
    patient: mockPatients[1],
    type: "intake",
    priority: "urgent",
    title: "High Pain Level Reported",
    message: "Robert Chen reported pain level 8/10 for tooth pain. Schedule immediate evaluation.",
    acknowledged: false,
    resolved: false,
    notes: [],
    createdAt: new Date(Date.now() - 30 * 60 * 1000),
  },
  {
    id: "alert2",
    patientId: "p4",
    patient: mockPatients[3],
    type: "appointment",
    priority: "high",
    title: "Missed Appointment",
    message: "James Williams missed their appointment on 09/02/2026. Contact to reschedule.",
    acknowledged: true,
    resolved: false,
    notes: [
      {
        id: "note1",
        text: "Left voicemail requesting callback.",
        author: "Receptionist",
        createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
      },
    ],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
  },
  {
    id: "alert3",
    patientId: "p3",
    patient: mockPatients[2],
    type: "prescription",
    priority: "high",
    title: "Prescription Expiring",
    message: "Maria Garcia's antibiotic prescription expires in 3 days. Schedule follow-up if needed.",
    acknowledged: false,
    resolved: false,
    notes: [],
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000),
  },
  {
    id: "alert4",
    patientId: "p6",
    patient: mockPatients[5],
    type: "intake",
    priority: "urgent",
    title: "Emergency Patient Check-in",
    message: "Michael Thompson has arrived for emergency broken tooth visit.",
    acknowledged: false,
    resolved: false,
    notes: [],
    createdAt: new Date(Date.now() - 15 * 60 * 1000),
  },
  {
    id: "alert5",
    patientId: "p1",
    patient: mockPatients[0],
    type: "follow-up",
    priority: "medium",
    title: "Follow-up Due",
    message: "Sarah Johnson's follow-up appointment is due. Last visit was 3 months ago.",
    acknowledged: true,
    resolved: false,
    notes: [],
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
  },
];
